before_install:
- env | sort
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -fyq install; fi
install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq clang libgtkglext1-dev
  libgtksourceview2.0-dev liblua5.1-0-dev freeglut3-dev libglu1-mesa-dev libgtk2.0-dev
  libgvnc-1.0-dev libg3d-dev; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq autoconf automake
  autopoint bash bison bzip2 cmake flex gettext git g++ gperf intltool libffi-dev
  libtool libltdl-dev libssl-dev libxml-parser-perl make openssl patch perl pkg-config
  python ruby scons sed unzip wget xz-utils g++-multilib libc6-dev-i386 nsis; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/local/lib:/opt/X11/lib/pkgconfig;
  fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gtkglext; brew install gtksourceview;
  brew install lua gettext; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew link gettext --force; fi
before_script:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then git clone https://github.com/mxe/mxe.git;
  fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd mxe; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 200 make MXE_TARGETS='i686-w64-mingw32.static'
  gcc; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 45 make MXE_TARGETS='i686-w64-mingw32.static'
  gtk2; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 45 make MXE_TARGETS='i686-w64-mingw32.static'
  lua; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 45 make MXE_TARGETS='i686-w64-mingw32.static'
  gtkglext; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 45 make MXE_TARGETS='i686-w64-mingw32.static'
  gtksourceview; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 45 make MXE_TARGETS='i686-w64-mingw32.static'
  freeglut; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH=`pwd`/usr/bin:$PATH; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd ..; fi
script:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then make clean all; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then make package; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then make clean; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then make TARGET=MINGW32 CROSS=i686-w64-mingw32.static-
  clean all; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then make TARGET=MINGW32 CROSS=i686-w64-mingw32.static-
  package; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then make TARGET=MINGW32 CROSS=i686-w64-mingw32.static-
  clean; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then make clean; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then make TARGET=OSX clean all; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then make TARGET=OSX package; fi
os:
- linux
- osx
language:
- c
compiler:
- clang
cache: apt
notifications:
  email: false
  irc:
    channels:
    - irc.freenode.org#cammill
    use_notice: true
git:
  depth: 5
matrix:
  allow_failures:
  - os: osx
deploy:
  provider: releases
  api_key:
    secure: EI1V4apdQ/iqXS1A/ScJl4G3kGO0kxtUqE1oXjS19O0VVEzWmjZwMenLaJXRdRwybd4aka0mn9tc1spLw8B79OWX+V72s61yOoKvDbo4B5YUo+Hcr9RrjBFNNr289D3EVBuNyb5SpWnL+yDf4zZ32yCNqSUom91sn61XnRW+yhckZtUXj8b9FgKGCTEtnqlU+5BNjme0Ikwz2jlZcUstJH9Bygmt5JTPPmqrmFC9pvHnvDcs6VVdV6lvbU2IgG6gn3wHgl7EiBLXvg2MBtIYsQrVfqPOjPl8//rLK41iG1fJDYrAFRzPe87mqJoQMT8XjZCT3zCFkY7ceEroiWc7/xqFLY9FuzF2i6ZXglAXUrCPyHa7QCdNowB92Fta9xrYCR/JO0+JFKz3ZYSOxzX8SHWRzas0RX0eGesXm2yED1lvBwfoImuqDWaG30Bs+cBoloKRnReafmc6KDWMOEVj65CLdvIP3XN+w2Ajzp3gjMjaU5w+gX66pgUozxFumZePcsGVbPAGXBce/x50TNpbR/x7GRbuyXwWAdf+KZFTi260N/IdU73/GxzBDiafGab/EjHFId5zyGg3xT7ysslTt1NZmn/yQwI4iuxU5fYzZ2QQMQAxcbTkORa51kfdV30t4vQUH542jH8FINXtUX5A40e+JSeaCREp4tAEtSROAX8=
  file: Windows/cammill-installer.exe
  on:
    repo: cammill/cammill
