before_install:
  - env | sort
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq clang libgtkglext1-dev libgtksourceview2.0-dev liblua5.1-0-dev freeglut3-dev libglu1-mesa-dev libgtk2.0-dev libgvnc-1.0-dev libg3d-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gtkglext; brew install gtksourceview; brew install lua; fi
os:
  - linux
  - osx
language:
  - c
compiler:
  - clang
cache: apt
script:
  - make
  - make clean
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#cammill"
    use_notice: true
