before_install:
  - env | sort
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -fyq install; fi

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq clang libgtkglext1-dev libgtksourceview2.0-dev liblua5.1-0-dev freeglut3-dev libglu1-mesa-dev libgtk2.0-dev libgvnc-1.0-dev libg3d-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq autoconf automake autopoint bash bison bzip2 cmake flex gettext git g++ gperf intltool libffi-dev libtool libltdl-dev libssl-dev libxml-parser-perl make openssl patch perl pkg-config python ruby scons sed unzip wget xz-utils g++-multilib libc6-dev-i386; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gtkglext; brew install gtksourceview; brew install lua gettext; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew link gettext --force; fi

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then git clone https://github.com/mxe/mxe.git; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd mxe; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 145 make MXE_TARGETS='i686-w64-mingw32.static' gcc; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 45 make MXE_TARGETS='i686-w64-mingw32.static' gtk2; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 45 make MXE_TARGETS='i686-w64-mingw32.static' lua; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 45 make MXE_TARGETS='i686-w64-mingw32.static' gtkglext; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 45 make MXE_TARGETS='i686-w64-mingw32.static' gtksourceview; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 45 make MXE_TARGETS='i686-w64-mingw32.static' freeglut; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH=`pwd`/usr/bin:$PATH; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd ..; fi

script:
  - make
  - make clean
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make PROGRAM=cammill.exe LIBS="-lm -lstdc++ -lgcc" CROSS=i686-w64-mingw32.static- COMP=i686-w64-mingw32.static-gcc PKGS="gtk+-2.0 gtk+-win32-2.0 gtkglext-1.0 gtksourceview-2.0 lua"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make clean; fi

os:
  - linux
  - osx
language:
  - c
compiler:
  - clang
cache: apt
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#cammill"
    use_notice: true
git:
  depth: 5
matrix:
  allow_failures:
    - os: osx
